#spring:
#  datasource:
#    username: root
#    password: 1997
#    url: jdbc:mysql://localhost:1122/example
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
